"""create snapshot table

Revision ID: 39b35b729b8a
Revises:
Create Date: 2022-12-17 02:11:03.666258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b35b729b8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wiki', sa.String(length=10), nullable=True),
    sa.Column('type', sa.Enum('recent', 'historical', name='snapshotenum'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('editors_male', sa.Integer(), nullable=True),
    sa.Column('editors_female', sa.Integer(), nullable=True),
    sa.Column('editors_neutral', sa.Integer(), nullable=True),
    sa.Column('edits_male', sa.Integer(), nullable=True),
    sa.Column('edits_female', sa.Integer(), nullable=True),
    sa.Column('edtis_neutral', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    # ### end Alembic commands ###
