"""Add period snapshots

Revision ID: eef31651f161
Revises: ef96d28f959a
Create Date: 2023-05-20 08:57:08.816268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef31651f161'
down_revision = 'ef96d28f959a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot', sa.Column('period_start', sa.DateTime(), nullable=True))
    op.add_column('snapshot', sa.Column('period_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot', 'period_end')
    op.drop_column('snapshot', 'period_start')
    # ### end Alembic commands ###
