"""Add limit

Revision ID: ef96d28f959a
Revises: 8a6a3d75b733
Create Date: 2022-12-17 02:43:31.513343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef96d28f959a'
down_revision = '8a6a3d75b733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot', sa.Column('limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot', 'limit')
    # ### end Alembic commands ###
